---
# This is an Ansible Playbook to bootstrap a server with proper directories and
# dotfiles. Do these before running the script:
# sudo apt install ansible
# wget https://github.com/knodir/dotfiles/blob/master/server-init.yml
# ansible-playbook server-init.yml
# 
# Once done, logout and login to start a shell with new config.
- hosts: localhost
  tasks:
    # - name: Append localhost to the list of known hosts
    #   blockinfile:
    #     dest: /etc/ansible/hosts
    #     block: |
    #       [targets]
    #       localhost ansible_connection=local

    - name: Install tmuxinator
      become: true
      apt: pkg=tmuxinator state=installed update_cache=true

    - name: Create workspace folders
      file:
        path: ~/workspace/dev
        state: directory

    - git:
        repo: https://github.com/knodir/dotfiles.git
        dest: ~/workspace/dev/dotfiles

    - name: Update bashrc
      copy:
        src: ~/workspace/dev/dotfiles/bashrc
        dest: ~/.bashrc

    - name: Update vimrc
      copy:
        src: ~/workspace/dev/dotfiles/vimrc
        dest: ~/.vimrc

    - name: Update tmux.conf
      copy:
        src: ~/workspace/dev/dotfiles/tmux.conf
        dest: ~/.tmux.conf

    - name: Create .tmuxinator folder
      file:
        path: ~/.tmuxinator
        state: directory

    - name: Put sample tmuxinator
      copy:
        src: ~/workspace/dev/dotfiles/sample.yml
        dest: ~/.tmuxinator/sample.yml

